### ISSUE TITLE
Doesn´t work

### ISSUE THREAD

**Issue by borochi** [Taknok/Qgisplugin-ClipMultipleLayers#10]
Doesn´t work the selection layer tab. I can´t select any layer to perform multilayer clip. Any idea?

**Comment by Taknok** [comment]
Hi,

Can you join a screenshot ? What is your Qgis version number ?

**Comment by borochi** [comment]
![image](https://user-images.githubusercontent.com/14899464/34419561-2aebd9f2-ebca-11e7-961e-f9ca305c02b4.png)

**Comment by borochi** [comment]
![image](https://user-images.githubusercontent.com/14899464/34419605-647fedf2-ebca-11e7-992c-dfbf082d0c6e.png)

**Comment by Taknok** [comment]
Do you have a vector layer in your project ? The vector layer is used as shape to cut. I tested it on windows 7 with Qgis 8.15 and it worked :/
Could you send me a sample of your project for testing purpose ?

**Comment by Taknok** [comment]
Is it solved ?
