### ISSUE TITLE
Can't ignore NULL geometries

### ISSUE THREAD

**Issue by JuKrz** [Taknok/Qgisplugin-ClipMultipleLayers#12]
I keep getting the error "Input layer A contains NULL geometries. Please check "ignore NULL geometries"..."

However, there is nowhere to choose this option, no check box, etc. 

I have also manually removed what I believe to be all NULL geometries from the attribute tables. It would also be nice to know which is 'layer A'.

**Comment by Taknok** [comment]
Thank you for the report !
Could you send me the layer that trigger the issue ? With it, I will be able to investigate.

**Comment by JuKrz** [comment]
I am not sure which one it was, I was eventually able to do it with the geoprocessing tools as a batch.  I though it was a maybe CRS problem, but fixing that didn’t help either and now all the shapeable I changed the CRS of are missing .dbf files (but had them yesterday). Luckily I still have the crippled ones from batch clipping.  

I will try to send, but they are on a different computer and now have no .dbf

Thanks 



  Dr. Judi Krzyzanowski BSc, MSc, PhD
  Tel. 613-395-9338 Fax. 1-877-233-2469
  Email: judi@krzyzanowski.ca <mailto:judik@primus.ca>
  Web:  http://www.krzyzanowski.ca <http://www.krzyzanowski.ca/>

**Comment by shtirlitsDva** [comment]
I don't know if it is related, but ClipMultipleLayers would display a warning box saying something about NULL when your masking polygon would try to clip a layer which didn't have geometry inside the clipping polygon.

**Comment by JuKrz** [comment]
That could be it, thank-you. However, after fixing all CRS (resaving the shp) it work in the batch clip.

Anyway, I now have the data as I need it, but it was frustrating. 

Thank-you, if I rebuild the rigs for any reason I will send.
