### ISSUE TITLE
Update to 3.2.x

### ISSUE THREAD

**Issue by shtirlitsDva** [Taknok/Qgisplugin-ClipMultipleLayers#13]
Hi
Is there a possibility for an update to 3.2.x?
Regards

**Comment by Taknok** [comment]
I'm quite busy right now, I will look at it in a month. Do not hesitate to remind me !

**Comment by Marteens** [comment]
What @shtirlitsDva  said :)

**Comment by shtirlitsDva** [comment]
> I'm quite busy right now, I will look at it in a month. Do not hesitate to remind me !

A friendly reminder with hope for a future version for 3.x.x qgis!

**Comment by Taknok** [comment]
Plugin 3.0.0 approval is pending... :)

**Comment by shtirlitsDva** [comment]
Great!
