### ISSUE TITLE
Installation error qgis 3.4.1

### ISSUE THREAD

**Issue by bellanz80** [Taknok/Qgisplugin-ClipMultipleLayers#14]
When installing the plug, a window opens with an error, which is attached to the file.

## Specifications

  - Version 3.0:
  - Platform: Windows 10 64 bit- v. 1809
   - QGIS 3.4.1

![error1](https://user-images.githubusercontent.com/38449926/48272458-3e3d3180-e404-11e8-9de0-d4bd2700fd80.PNG)

**Comment by Taknok** [comment]
Thank you for the report !
This issue is on 3.0.0 (for the plugin version), try to uninstall and install 3.0.1: http://plugins.qgis.org/plugins/ClipMultipleLayers/version/3.0.1/

**Comment by bellanz80** [comment]
Yes!!! Now it works! thank you!
Luca
