### ISSUE TITLE
Can't seem to use this with .nc raster files

### ISSUE THREAD

**Issue by tony129** [Taknok/Qgisplugin-ClipMultipleLayers#15]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by Taknok** [comment]
Hi,

Could you provide a .nc raster file ?

**Comment by Taknok** [comment]
Closed due to inactivity. Comment to re-open it.
