### ISSUE TITLE
Can't Install Latest Version

### ISSUE THREAD

**Issue by wtc1909** [Taknok/Qgisplugin-ClipMultipleLayers#17]
Install succeeds

Won't install: Error Message: Couldn't load plugin 'ClipMultipleLayers' due to an error when calling its classFactory() method 

Try to install

  1.
  1.
  1.

## Specifications

  - Version:
QGIS3.12 on Windows 10 64-bit
  - Subsystem:

**Comment by Taknok** [comment]
Just test on a fresh install of QGIS 3.10.4-1 and it works fine. I will check on 3.12.

**Comment by Taknok** [comment]
I installed the plugin on a windows 10 and QGIS 3.12.1 and the test project successfully. Which OS are you using ?

**Comment by Taknok** [comment]
Closed due to inactivity.
