### ISSUE TITLE
3.4.13-Madeira on OSX python code error

### ISSUE THREAD

**Issue by NinaCaldarella** [Taknok/Qgisplugin-ClipMultipleLayers#18]
## Expected Behavior
I have attempted applying the Clip Multiple Layers tool to clip 2 raster files with height data to a polygon vector layer.

## Actual Behavior
But it does not Clip anything and ends in a Python Error.
I have upgraded the GDAL plugins through QGIS.

## Steps to Reproduce the Problem

  1. load raster layers
  1. draw polygon
  1.plugins > clip multiple layers

## Specifications
An error has occurred while executing Python code: 

_core.QgsProcessingException: Error: Algorithm gdal:cliprasterbymasklayer not found 

  - Version: 3.4.13-Madeira
  - Platform: OS Catalina
  - Subsystem:

**Comment by Taknok** [comment]
Hi,
The issue is probably triggered because gdal was not installed with your Qgis version. Is issue still present when Gdal is installed ?
I apology for HUGE delay

**Comment by Taknok** [comment]
Inactive. Comment and I will re-open this issue.
