### ISSUE TITLE
Please consider adding it to Processing

### ISSUE THREAD

**Issue by pcav** [Taknok/Qgisplugin-ClipMultipleLayers#3]
So it can be included in more complex workflows, batched, etc.

**Comment by Taknok** [comment]
"No worries, I'm here to help :)" -> Thank :)
OK for gnome popup, I gonna test on linux and edit the UI
I don't understand "So it can be included in more complex workflows,
batched, etc." I understand the "translate", but not what it "mean/refer to
"
Thank for the approval :)

2015-05-20 13:50 GMT+02:00 Paolo Cavallini notifications@github.com:

**Comment by pcav** [comment]
Il 20/05/2015 13:58, Taknok ha scritto:

> "No worries, I'm here to help :)" -> Thank :)
> OK for gnome popup, I gonna test on linux and edit the UI
> I don't understand "So it can be included in more complex workflows,
> batched, etc." I understand the "translate", but not what it "mean/refer to

Adding the plugin to Processing framework would give several advantages.

## All the best.

Paolo Cavallini - www.faunalia.eu
QGIS & PostGIS courses: http://www.faunalia.eu/training.html

**Comment by Taknok** [comment]
Ok thank, I did'nt know about the existence of processing framework, I will
read and search about it :)

2015-05-20 14:02 GMT+02:00 Paolo Cavallini notifications@github.com:

**Comment by Taknok** [comment]
Well the script for the processing framework is ready, but I don't know how to share it... I search on qgis website and google, but without success :/ Do you know how to ?

**Comment by pcav** [comment]
Best if you ask for directions on the qgis-dev mailing list, or check some other sublugins (e.g. lwgeomprovider, lecos).
Thanks.

**Comment by Taknok** [comment]
In Qgis 2.8, to clip a raster the function [`gdalogr:cliprasterbymasklayer`](https://docs.qgis.org/2.8/en/docs/user_manual/processing_algs/gdalogr/gdal_extraction.html#clip-raster-by-mask-layer) can be used. To clip layers the function [`qgis:clip`](https://docs.qgis.org/2.8/en/docs/user_manual/processing_algs/qgis/vector_overlay_tools.html) can be used.
