### ISSUE TITLE
Output is empty for WFS vector layers

### ISSUE THREAD

**Issue by shtirlitsDva** [Taknok/Qgisplugin-ClipMultipleLayers#5]
When trying to clip WFS vector layers the output folder is empty.

**Comment by shtirlitsDva** [comment]
I have a possible cause:

This code:
`output = path_project + "/output/vectors/clip_" + layer.name() + ".shp"`

calls for layer.name()

my WFS layers are named as an example: "kms: MAST"

the ":" character is illegal in a path name (im on Windows)

I propose adding a routine to clean the path name from characters not allowed in a path name.

**Comment by shtirlitsDva** [comment]
I can confirm that the layer names containing characters illegal in a path name was the cause.

**Comment by Taknok** [comment]
Hello,

I built this plugin on a linux computer :/. I will check a path cleaner for
next version, thank you for your report :)
