### ISSUE TITLE
Clip Multiple Layers doesn't work with QGIS 2.18.0 on Windows 8 platform

### ISSUE THREAD

**Issue by danielao222** [Taknok/Qgisplugin-ClipMultipleLayers#6]
Clip Multiple Layers doesn't work with QGIS 2.18.0; it appears be installed correctly on Python plug-in, and it makes me able to open it and select the clip layer, but when I start with OK button, it only creates the directories "output\rasters and output\vectors" but without creating the clipped layer there inside .

Versione installata: 0.1.3 with QGIS 2.18.0 on Windows 8 platform

**Comment by shtirlitsDva** [comment]
Hi, I had same issue, please see [this](https://github.com/Taknok/Qgisplugin-ClipMultipleLayers/issues/5) thread and confirm that your layer name does not contain characters not allowed in a path name.

**Comment by danielao222** [comment]
Hi, thank you. I saw your post. I think it's not my case, because I used this version of Clip Multiple Layers on QGIS 2.8 for a long time, without any problems. The separator symbol in path is "/" and i don't use special caracters or empty spaces (i use only "-" or "_"). I already tried on simplified paths and filenames, but without success.

**Comment by Taknok** [comment]
Hello,

Could you add a screen of the error here ?

**Comment by danielao222** [comment]
Hi, thank you. I would like post some error message, but it doesn't give any message ... Simply it doesn't run. Plug-in creates the directories "output" and so on, but it doesn't appear working. 
It doesn't appear even the status bar of the working progress. Sorry

**Comment by Taknok** [comment]
I updated the plugin, could you tell me if this update solve it ?

**Comment by danielao222** [comment]
Hello, thank you very much! Your upgrade works very well on QGis v.2.18. I want you know that your plug-in is very very useful for us. I appreciate your effort maintain it on new versions of QGis. Thank you again. Daniel, from Rome, Italy

**Comment by Taknok** [comment]
Ok thank you. I'm glad to see you appreciate it :)
