### ISSUE TITLE
Download limit reached

### ISSUE THREAD

**Issue by shtirlitsDva** [Taknok/Qgisplugin-ClipMultipleLayers#7]
When executing the plugin command, server returns an error on many layers: "kms:Vejmidte: The download limit has been reached. You may want to check the 'Only request features overlapping the view extent' option to be able to zoom in to fetch all data."

The final result looks good though.

Does the clip command have a limitation to the area of the clipping polygon?

Mine polygon wasn't big and I did't request too many features.

**Comment by Taknok** [comment]
The plugin use other built in features of qgis, maybe the bug comes from there. I have never seen this error message. I gonna look at it asap. To help me, which version of qgis and plugin are you using ?

**Comment by shtirlitsDva** [comment]
I am sorry, this is not an error from the plugin but the server, so I close this issue.
