### ISSUE TITLE
current version contains a folder "__MACOSX" which causes trouble

### ISSUE THREAD

**Issue by thbaumann** [Taknok/Qgisplugin-ClipMultipleLayers#9]
The current version
http://plugins.qgis.org/plugins/ClipMultipleLayers/version/0.1.6/download/
contains a folder called "__MACOSX" which is considered as a broken extension in QGIS

![grafik](https://user-images.githubusercontent.com/20082727/30908569-3886160c-a37e-11e7-8411-60ace6c40fac.png)

**Comment by Taknok** [comment]
Thank you for the report. Next version will be ok :)
